Remove complex loops in tests
EBI-Metagenomics/MGnifyR pull request #28
Opened 2023-06-14 10:03 UTC by Daenarys8

- Removed complex loops in tests used to test wrong user arguments. 
- Replaced with sequential tests for a similar objective.

2023-06-15 06:02 UTC, TuomasBorman commented on tests/testthat/test-MgnifyClient.R
> +    # Expect errors when input is wrong
This comment is little bit extra since that is already told above

2023-06-15 06:14 UTC, TuomasBorman commented on tests/testthat/test-MgnifyClient.R
>      mg <- MgnifyClient()
This line can be deleted

2023-06-15 06:19 UTC, TuomasBorman commented on tests/testthat/test-MgnifyClient.R
> +    )
These 3 tests test actually the same thing. They test if the `url` is found from the web. (Run the code inside the `expect_error` and you will see the error message.

For example, the `username` parameter can get only character value based on the documentation of the function. How we test that the input tests work correctly?

1. Determine what you want to test. For example,` username` parameter's inputs.
2. Determine which is the correct input type. (Sometimes it is determined only in class level, sometimes the input must be more specific, for example, specific method name.) --> From the documentation we can see that `username` must be a single character value.
3. Determine what are the tested values. Since character is allowed, wrong values are integer, vector, boolean...
4. Let all the other values be default values and create tests that test that error occurs when `username` value is incorrect type.

I would test `username`'s input tests like this:


```
expect_error( MgnifyClient(username = TRUE) )
expect_error( MgnifyClient(username = 10.1) )
expect_error( MgnifyClient(username = c("test", "test2")) )
```

Modify the tests also in other files accordingly and check that they work correctly. (Meaning that you run for example `MgnifyClient(username = TRUE)` --> it should give an error that says that the `username` must be character.)

2023-06-16 12:41 UTC, Daenarys8 commented on tests/testthat/test-MgnifyClient.R
> +    # Expect errors when input is wrong
Oh I missed this.

2023-06-16 12:42 UTC, Daenarys8 commented on tests/testthat/test-MgnifyClient.R
>      mg <- MgnifyClient()
I missed this too:)

2023-06-16 12:43 UTC, Daenarys8 commented on tests/testthat/test-MgnifyClient.R
> +    )
Ah, yes, thanks for the clarification. I have made some changes.

2023-06-26 11:19 UTC, TuomasBorman requested changes
Good, looks better! See those comments

General comment: there are still some lines where you are testing multiple things. Each line should have only one parameter that you are testing (and MgnifyClient object since it is required).

It is easier to create this tests without expect_error() --> after you get the correct error message, you can put it inside the function

2023-06-26 11:19 UTC, TuomasBorman commented on tests/testthat/test-MgnifyClient.R
> +                              password = 28))
You can put these to same line

2023-06-26 11:19 UTC, TuomasBorman commented on tests/testthat/test-MgnifyClient.R
> +                              password = 28))
And you can actually remove also username arfuments here

2023-06-26 11:19 UTC, TuomasBorman commented on tests/testthat/test-MgnifyClient.R
> +        cacheDir = tree,
here also, put to same line and remove username and password argumetns

2023-06-26 11:19 UTC, TuomasBorman commented on tests/testthat/test-MgnifyClient.R
> +            url = TreeSE,
This line does not test anything, becase there is no TreeSE object --> it leads to an error before the input check

2023-06-26 11:19 UTC, TuomasBorman commented on tests/testthat/test-doQuery.R
> +        accession = c(TreeSE, "phyloseq"),
There is not object named TreeSE?

2023-06-26 11:19 UTC, TuomasBorman commented on tests/testthat/test-getMetadata.R
> +    ))
expect_error(getMetadata( mg, accession = "studies", use.cache = "test" ))

2023-06-26 11:19 UTC, TuomasBorman commented on tests/testthat/test-getMetadata.R
> +        verbose = TRUE
remove verbose here

2023-06-26 11:19 UTC, TuomasBorman commented on tests/testthat/test-getMetadata.R
> +        verbose = TRUE
remove verbose

2023-06-26 11:19 UTC, TuomasBorman commented on tests/testthat/test-getResult.R
> +    expect_error(suppressWarnings(getResult(
Remove all the suppressWarnings

2023-06-26 11:19 UTC, TuomasBorman commented on tests/testthat/test-searchAnalysis.R
> +            accession = assembly,
There is no assembly object, this leads to an error before the input test

2023-06-26 11:20 UTC, TuomasBorman commented
There are also lots of line breaks that does not improve the readibility

2023-06-27 07:29 UTC, Daenarys8 commented on tests/testthat/test-MgnifyClient.R
> +                              password = 28))
ACK

2023-06-27 07:29 UTC, Daenarys8 commented on tests/testthat/test-MgnifyClient.R
> +        cacheDir = tree,
ACK

2023-06-27 07:30 UTC, Daenarys8 commented on tests/testthat/test-MgnifyClient.R
> +            url = TreeSE,
ACK

2023-06-27 07:30 UTC, Daenarys8 commented on tests/testthat/test-doQuery.R
> +        accession = c(TreeSE, "phyloseq"),
ACK

2023-06-27 07:31 UTC, Daenarys8 commented on tests/testthat/test-searchAnalysis.R
> +            accession = assembly,
ACK

2023-06-27 07:32 UTC, Daenarys8 commented
Oh  the line breaks were a result of auto reformatting code in  R. Have fixed it for better readability.

2023-07-03 12:27 UTC, TuomasBorman requested changes
Good! Almost there

2023-07-03 12:27 UTC, TuomasBorman commented on tests/testthat/test-getMetadata.R
> +    expect_error(getMetadata(mg, accession = "test", verbose = 10))
accession is wrong here, replace with correct value so that use.cache ad verbose are tested

2023-07-03 12:27 UTC, TuomasBorman commented on tests/testthat/test-getResult.R
> +    expect_error(getResult(mg, accession = "taxonomy-ssu", verbose = "TreeSE"))
`accession` should have a correct accession ID when you test other parametrs than `accession` . CHeck parameter description. Correct accession ID is e.t. "MGYA00097621"

2023-07-03 12:27 UTC, TuomasBorman commented on tests/testthat/test-searchAnalysis.R
> +    expect_error(searchAnalysis(mg, type = "studies", accession = "test", use.cache = "studies"))
accession is incorrect

2023-07-03 12:27 UTC, TuomasBorman commented on tests/testthat/test-searchAnalysis.R
> +    expect_error(searchAnalysis(mg, type = "samples", accession = "test", verbose = "Tree"))
accession is incorrect

2023-07-14 19:22 UTC, TuomasBorman commented on tests/testthat/test-getResult.R
>      if (!skip) {
This skip thing can be deleted

2023-07-14 19:23 UTC, TuomasBorman commented on tests/testthat/test-MgnifyClient.R
> +    expect_error(MgnifyClient(password = TRUE))
How about if the input is vector?

2023-07-14 19:23 UTC, TuomasBorman commented on tests/testthat/test-MgnifyClient.R
> +    expect_error(MgnifyClient(password = TRUE))
Same applies to others

2023-07-14 19:24 UTC, TuomasBorman commented on tests/testthat/test-getFile.R
> +    expect_error(getFile( mg, url = "taxonomy--ssu", use.cache = 10))
These checks fail because of url is wrong. Other arguments are not checked (applies to some other tests also)

2023-07-14 19:41 UTC, TuomasBorman commented on tests/testthat/test-getResult.R
> +    expect_true(is.character(res$`interpro-identifiers`$accession) && is.character(res$`interpro-identifiers`$description) && is.numeric(res$`interpro-identifiers`$MGYA00097621))
Sorry, the function changed little bit. That is why there is an error in checks. Here this old version (line 49-52) should work, so modify line 35 accordingly

2023-09-27 12:13 UTC, TuomasBorman approved these changes

2023-09-27 13:48 UTC, merged